language: node_js
install:
  - "npm install mocha -g"
  - "npm install chai"
  - "npm install -g"

node_js:
  - "7"
  - "6"

notifications:
  email:
    recipients:
      - team@jovo.tech
    on_success: never
    on_failure: always