language: node_js
install:
  - "npm install mocha -g"
  - "npm install jovo-cli -g"
  - "npm install"

node_js:
  - "7"
  - "6"
  - "5"
  - "4"

notifications:
  email:
    recipients:
      - team@jovo.tech
    on_success: never
    on_failure: always